// <auto-generated />
using System;
using FlightSearchAssingment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightSearchAssingment.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221128184314_PriceFix")]
    partial class PriceFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("FlightSearchAssingment.Models.Flight", b =>
                {
                    b.Property<string>("FlightId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arrival")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Departure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FlightSearchAssingment.Models.Itenerary", b =>
                {
                    b.Property<string>("IteneraryID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IteneraryID");

                    b.HasIndex("FlightId");

                    b.ToTable("Iteneraries");
                });

            modelBuilder.Entity("FlightSearchAssingment.Models.Prices", b =>
                {
                    b.Property<string>("PricesId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AdultPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IteneraryID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PricesId");

                    b.HasIndex("IteneraryID")
                        .IsUnique();

                    b.ToTable("PriceList");
                });

            modelBuilder.Entity("FlightSearchAssingment.Models.Itenerary", b =>
                {
                    b.HasOne("FlightSearchAssingment.Models.Flight", "flight")
                        .WithMany("Iteneraries")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("flight");
                });

            modelBuilder.Entity("FlightSearchAssingment.Models.Prices", b =>
                {
                    b.HasOne("FlightSearchAssingment.Models.Itenerary", null)
                        .WithOne("PriceList")
                        .HasForeignKey("FlightSearchAssingment.Models.Prices", "IteneraryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlightSearchAssingment.Models.Flight", b =>
                {
                    b.Navigation("Iteneraries");
                });

            modelBuilder.Entity("FlightSearchAssingment.Models.Itenerary", b =>
                {
                    b.Navigation("PriceList")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
